SEARCH_RESOURCES_LIST='{"eugenius": "Eugenius", "smart": "Smart", "smartxr-cane": "SmartXR (cane)"}'
SEARCH_INDEX_CONFIG_SMARTXR_CANE='{"msbootcamp20231212": "MS Bootcamp", "msbootcamp20231212-index": "BC Whole Docs"}'
SEARCH_INDEX_CONFIG_EUGENIUS='{"library-wholedoc-index": "Library Whole Docs", "library-chunks-index": "Library Chunked Docs", "gsc-sourcedocs-index": "GSC Whole Docs", "gsc-sourcedocs": "GSC Chunked Docs"}'
SEARCH_INDEX_CONFIG_SMART='{"index-one": "Index One", "index-two": "Index Two", "index-three": "Index Three"}'
SEARCH_API_KEY_SMARTXR_CANE='-= Search Key =-'
SEARCH_API_KEY_EUGENIUS='-= Search Key =-'
SEARCH_API_KEY_SMART='-= Search Key =-'
SEARCH_INDEX_TYPE_EUGENIUS_GSC_SOURCEDOCS='standard-chunked'
SEARCH_INDEX_TYPE_EUGENIUS_LIBRARY_CHUNKS_INDEX='standard-chunked'
SEARCH_INDEX_TYPE_SMARTXR_CANE_MSBOOTCAMP20231212='standard-chunked'
SEARCH_API_VERSION='2023-08-01-preview'
SEARCH_PAGE_SIZE='30'
OPENAI_API_ENDPOINT='https://eugenius.openai.azure.com'
OPENAI_API_KEY='-= Search Key =-'
OPENAI_DEPLOYMENT_ID='GPT4-32'
OPENAI_API_VERSION='2023-08-01-preview'
